name: Check
description: Run CI checks
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.23
    - shell: bash
      run: make build
    - shell: bash
      run: make test
